dataset_path: ytan-ucr/mu_llava_mark_zuckerberg
dataset_kwargs:
  token: True
task: "mu_mark"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mu_doc_to_visual
doc_to_text: !function utils.mu_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.mu_process_result
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: FA
    aggregation: !function utils.mu_aggregation_result
    higher_is_better: false
metadata:
  - version: 0.0